### PR TITLE
Convert over to python 3

### PR DESCRIPTION
**Pull request by moon-chilled**
It uses string instead of bytes now -- might slow it down, theoretically, but *shrug*.

### CODE REVIEW

**Comment by elextr** [comment]
Neat.

I don't think we should just replace the python2 version without LOTS of testing, so I created a repository python3 inside teh asciidoc organisation, if you could make this issue there it can then be converted and tested without removing the original.

**Comment by moon-chilled** [comment]
Alright, I'll move it over there.  There are also some problems with the tests (beyond just moving to python3) that I have yet to sort out, so it's not done *yet*.  I'm closing this for now since it's moving to the other repo.  Also, might want rename the repository to something other than "python3," it makes it seem like you have your own fork of python.  Maybe asciidoc-3?

**Comment by elextr** [comment]
Good point about the name, lemme see if I can find where github hides the menu for that, probably better you don't clone it until then.

**Comment by elextr** [comment]
Ok, asciidoc3, thanks for actually completing the job, this is the first complete conversion I have ever seen.

**Comment by moon-chilled** [comment]
Well...semi-complete.  My only "test" was on the readme, which is pretty simple.  There are still a bunch of other misc problems to kink out.

**Comment by elextr** [comment]
Thats why I wanted a different repo, I expect your first PR to be fairly major, we can discuss more there.

**Pull request closed without merging**
