### PR TITLE
Fixing bug for embedded image corruption

### PR DESCRIPTION
**Pull request by bruinsg**
Hi,
I fixed a bug where and image was corrupted when using the image-inlinemacro for xhmtl11.
The issue was present on both cygwin and Ubuntu using python 2.7

I also fixed the makefile since the latex2png was renamed to latex2img.
With these changes I was able to install and build my documents.

Thanks,
Peter Bruin

### CODE REVIEW

**Comment by elextr** [comment]
I think all the encoding calls in html5 and xhtml11 should be sys3, not just one.  The fact that (as discussed on ML) it often works with sys is just luck and depends on the exact content of the encoding.

Thanks for catching the build system fixes.

**Comment by bruinsg** [comment]
Ok, can I leave that to you? Don't want to change things I can't test..

**Comment by elextr** [comment]
Sure but it could be a while.

**Comment by bruinsg** [comment]
I have rebased the pull request. It is still an issue and corrupt roughly 25% of my images

**Comment by bruinsg** [comment]
Replaced by Pull request #47

**Pull request closed without merging**
