### PR TITLE
Merge quoted

### PR DESCRIPTION
**Pull request by powerman**
This is just 3 other pull requests merged together in single request for convenience (they change same lines for there are some conflicts): #55 #56 #57 - use this one if you decide to apply all 3.

### CODE REVIEW

**Comment by powerman** [comment]
Added #60 plus fix to make all changes merged here work together.
Example for testing (fix everything marked "Wrong"):

```
- Wrong: [red]#unquoted#-
- Wrong: 'em'[red]#unquoted#*bold*

- Right: ~sub [is] here~ ^super [is] here^
- Wrong: ~sub [red]#unquoted#~ ^[red]#unquoted# super^
```

**Comment by mojavelinux** [comment]
Thanks! These changes are really going to get this syntax moving again.

In this case it's probably best to handle this change as multiple commits on a single pull request (i.e., this one) so the changes can be easily tested. I'll do some testing myself, though I'd like to get some other people's eyes on it as well. I'll lobby for some review.

**Comment by elextr** [comment]
As I said on the other PR, if its confirmed good by other vim users then happy to accept, and thanks for making it easier by combining.

**Comment by mojavelinux** [comment]
I can confirm that the changes made fix all the test cases provided. No errors are apparent after looking through several documents.

What might help in the long run is to have a document that verifies as many cases as possible so that we can visually confirm that the syntax file is sound. Even better would be if someone could figure out how to write automated tests :)

**Comment by aerostitch** [comment]
@powerman It seems this repo will no longer accept PR as the latest release has been cut a while ago but https://github.com/asciidoc/asciidoc-py3 would.
If you still want this PR integrated in asciidoc, do you mind pushing it there please?
Once done I think you can close this one.
Thanks!

**Pull request closed without merging**
