### PR TITLE
Create lang-pl.conf

### PR DESCRIPTION
**Pull request by ciampix**
Support for nationalization for Polish, from Kerusey Karyu keruseykaryu@o2.pl

### CODE REVIEW

**Comment by ciampix** [comment]
Would you merge this please? You can also take the lang-ja.conf from the kicad-doc patch to asciidoc. We have some native speakers that can assure that those conf files are correct.

**Comment by elextr** [comment]
Well, nobody has objected since March so I guess its ok.

**Comment by ciampix** [comment]
Many thanks! What about the ja version? How about insert that too? If you are not sure ask around... the file is so small that I think will suffice even google translator...

**Comment by elextr** [comment]
There is only one file in this pull request.  And their is already lang-ja.conf.

**Comment by ciampix** [comment]
Ok sorry & many thanks!

**Pull request merged**
