### PR TITLE
Do not depend on deprecated md5

### PR DESCRIPTION
**Pull request by florentx**
Change the filters `latex` and `music` to avoid depending on a deprecated module.

Module `hashlib` exists since Python 2.5.
https://docs.python.org/2/library/hashlib.html

### CODE REVIEW

**Comment by michel-kraemer** [comment]
+1
I'm not a Python expert though, so someone else should approve and merge.

Cheers,
Michel

**Comment by elextr** [comment]
Unfortunately hashlib is only available on 2.5 or newer, but Asciidoc states it supports 2.4 as well.  My understanding was that was because of Jython support, but Jython has been at 2.5 for several years now so that impediment to requiring a newer version no longer exists.

Nevertheless I think we should request comment on the ML just in case there is some impediment we don't know about, then move the required version to 2.5 before this is committed.

**Comment by florentx** [comment]
Funny, because until #27 is merged, the latex filter breaks compatibility with Python < 2.7 ;)

I think it would be a good move to bump the minimal Python version to 2.5 (or 2.6), because it will be difficult to avoid breaking compatibility if we don't have all the obsolete Python versions to run the tests. And Travis-CI covers only Python >= 2.6.
However in my working environment, sometimes I run the tests with Python 2.5 too.

**Comment by elextr** [comment]
So if there are any users of versions of Python older than 2.7 they can't use the latex filter since there have been no complaints :)  Although the change has been since the previous release.

The argument that older versions are not generally available is a good point in favour of updating the required version even further.

Perhaps you could point out the argument for 2.6 in reply to the ML RFC I just sent.

**Comment by aerostitch** [comment]
And I think this one should be merged before #115 too. If we do a release, maybe not ship deprecated deps. ;)

**Comment by elextr** [comment]
@aerostitch for Python 2 md5 is never going to be removed despite deprecation.  I don't want to make any changes the day before release.

**Comment by aerostitch** [comment]
Makes sense. Thanks!

**Comment by aerostitch** [comment]
Seems this change has been integrated in https://github.com/asciidoc/asciidoc-py3
@elextr as the last release on this repo has already been cut and this repo deprecated, should we keep this one open?

**Comment by elextr** [comment]
@aerostitch yes, done.

**Pull request closed without merging**
