### PR TITLE
Prepare 8.6.10 release

### PR DESCRIPTION
**Pull request by bmwiedemann**
I really would love to see a new release to include it in openSUSE.
Not just for issue #103

The ChangeLog might need some more love from someone more involved.
And after this is merged and tested, a 8.6.10 tag should be added.

### CODE REVIEW

**Comment by elextr** [comment]
Looks good, thanks for doing this.

Only suggestion is to make the git reference in the changelog `asciidoc:8.6.9...asciidoc:8.6.10`.

**Comment by bmwiedemann** [comment]
I updated the link. I had thought about it and had not done it to not have broken links in the PR, but it is good because it will magically start to work once the tag is created.

**Comment by elextr** [comment]
The failing Travis has nothing to do with this PR, will just leave it for a few days to make sure there are no other suggestions/contributions then commit.

Thanks again.

**Comment by elextr** [comment]
Hopefully release is good, thanks again for making the release PR.

**Pull request merged**
