### PR TITLE
Changing behavior when filter is not found

### PR DESCRIPTION
**Pull request by aerostitch**
Hi,

When a filter is not installed (take here the example of `source-highlight`), asciidoc doesn't notice it, just throws a warning and don't render the document as if the filter was not needed.

The error is, in our case:

```
$ ./asciidoc.py /tmp/toto
/bin/sh: 1: source-highlight: not found
asciidoc: WARNING: toto: line 13: filter non-zero exit code: source-highlight -f xhtml -s shell: returned 127
asciidoc: WARNING: toto: line 13: no output from filter: source-highlight -f xhtml -s shell
```

What I propose is to have the `filter not found: %s` warning message if filter is not found and that the result of the filter_lines would be the "lines" args, so that, in our case, that would show the following warning, and the block of code will still be written in the bloc of code.

```
$ ./asciidoc.py /tmp/toto
asciidoc: WARNING: toto: line 13: filter not found: source-highlight
```

Joseph

### CODE REVIEW

**Comment by elextr** [comment]
The first error is not because a filter is not installed, it is because a program `source-highlight` used by the `source` filter is missing.

It is giving the user inaccurate information to transform this into a missing filter message.

**Comment by aerostitch** [comment]
Yes, that's what I wanted to say, sorry, I perhaps didn't get that explain clearly enough.

**Comment by elextr** [comment]
Your new message says that a filter named `source-highlight` was not installed.  This is wrong, there is no filter called `source-highlight`.

The filter perhaps should check if its dependencies are present, though that is often difficult in practice if they are executables since they can exist in different places on different systems.  But that is the filter's job, not asciidoc since in general it does not know what dependencies the filter has.

**Comment by elextr** [comment]
PS don't forget the `source` filter can use either `source-highlight` or `pygments`.

**Comment by aerostitch** [comment]
I only display the cmd variable given to the function as filter. This way, you know exactly which command is missing.
Should I change the message to: 'filter command not found: %s' % cmd ?

Code is:

```
message.warning('filter not found: %s' % cmd)
```

**Comment by elextr** [comment]
But most of the filters actually give the name of a python script that is part of the filter as the command.

That script may then execute something else.  Look at the graphviz filter, the `graphviz2png.py` script eventually runs commands called `dot`, `neato` etc

**Comment by aerostitch** [comment]
Then I think that the check of the shell command existence should be done also at the filter level.

Perhaps would it be good to have an "asciidoc-utils.py" that would contain, amongst others, a function that checks that the given shell command exists and output a clear error message when it does not. This way filters could use it and avoid code redundancy.

The things that changed will only help to have a clearer error message when checking the existence of the shell commands executed at asciidoc level. Not at the filters level.
So if the file graphviz2png.py is missing, you'll have a clear error message saying: `filter not found: graphviz2png.py` (yes, in that case, the proposed `'filter command not found: %s' % cmd` would seems even clearer to me).

**Comment by elextr** [comment]
Yes it is a filter problem as I said above.

Feel free to try to find a way of checking the existence of any particular command, but, as I also said above, in general its not easy.  A command might be a shell built-in, a specified path (either relative or absolute) or (on Linux at least) exist in some directory that is in the PATH environment variable.  But I'm not sure what the mechanism is on windows, probably it involves some registry settings.  Not to mention Windows directories with spaces in them.

And just because it exists doesn't mean its an executable (or script) that will run, you need to test more for that.  And then there are problems with which version of the command you have.  Don't get me started ... oh I have :)

In general checking this isn't something that applications should be doing.  Not installing dependencies is a user or packaging problem.  The message says what can't be run.  If a filter wants to detect a failure and provide a more useful message thats fine, so long as the message is useful and relevant.

**Comment by aerostitch** [comment]
You're right.
I reset my changes and just captured the error message to display it just after the non-zero return code so it seems clearer that the error message is related to the return code.

When there's no output, I also make the function return the input "lines" parameter so in case of filters that do text transformation, the untransformed lines will be outputed instead of nothing.

Is it better this way?

**Comment by edusantana** [comment]
I don't know if it helps, but I would use:

```
which source-highlight
which pygmentize
```

to get the path of the program in linux, If they don't exist it will return nothing. I don't know how to do it in python.

**Comment by elextr** [comment]
@edusantana unfortunately `which` is not available on all platforms that Asciidoc is used on.

**Comment by elextr** [comment]
@aerostitch no, although it generates a warning message for no output, it is actually a valid thing.  The filter may be deciding to include or not include content.  Asciidoc shouldn't override that.

**Comment by aerostitch** [comment]
Hi Lex,

Seems that on both windows and Unix/Linux, the return code "127" means "command not found", so I made another modification to the commit to take this in account.
I removed the "return lines" in the case of an empty result and make the "return lines" only in case of a command not found with a clearer error message.

Does that sound better to you?
Joseph

**Comment by aerostitch** [comment]
Hi Lex,

Sorry for the late answer.
Ok, so This PR was a bad idea. I close it.

Joseph

**Pull request closed without merging**
