### PR TITLE
Add missing example files

### PR DESCRIPTION
**Pull request by sm0svx**
There are a lot of example files missing that are referenced from the AsciiDoc main page at http://www.asciidoc.org/. This PR will add these files to the gh-pages branch.

The added files have not been regenerated but rather copied from http://www.methods.co.nz/asciidoc/.

### CODE REVIEW

**Comment by sm0svx** [comment]
I seem to have missed some example files. I'll add them too.

**Comment by mojavelinux** [comment]
Thanks for pointing this out!

I'm pretty sure that the gh-pages branch is populated by a (new) script. Therefore, the correct way to solve it is to update the script. Adding the files manually is a one-time solution and will be out of date the next time the site is published.

**Comment by sm0svx** [comment]
Sounds logical. Maybe it would not hurt to merge this PR anyway to fix the immediate problem until the script is fixed. I'll leave that for someone else to decide. Just close the PR if you don't want it.

**Comment by mojavelinux** [comment]
I linked the related issue. I actually can't remember where we left the publishing of the gh-pages branch. It certainly doesn't hurt to merge this to cover the broken links in the short term...but it definitely needs to be addressed in whatever script is making the gh-pages branch asap.

**Comment by sm0svx** [comment]
:+1:

**Pull request merged**
