### PR TITLE
Changing the behavior of the Last Updated field at the bottom of the page

### PR DESCRIPTION
**Pull request by aerostitch**
Hello,

First things first, thanks for your great work on this tool.

As explained in both links I propose to change the behavior of the footer-text:
https://code.google.com/p/asciidoc/issues/detail?id=29
https://groups.google.com/forum/#!topic/asciidoc/EsOmfFrlGqQ
## Context:

I (and other people, for example: http://bugs.debian.org/656736) had the issue of the modification of the "Last updated" field at the bottom of the generated page that gives the modification date of the page (not the revision date) when you use asciidoc to generate HTML pages.

For example, I'm using a central git repo for the text pages and generate the html pages using a batch. When you update repo that is used for the batch it can be at another date than the date of the revision, so the "Last updated" field at the end of the page can be confusing.
## My proposition:

What I did in the patch is I used a new standard attribute named "footer-style" (you can change it if you want!) that could take 3 values:
- default :or not defined, same as currently)
- none : not displaying the footer-text section
- revdate : displays the revision date instead of the source file modification date
  Any other value will display only the version number from the footer-text section(if defined).

On Lex's advice I put all the logic in the xhtml11.conf backend file in order to only have a template call in the language files.
This time I updated all language files.

Please tell me if you have any remarks about this pull request.

Thanks in advance,
Joseph

### CODE REVIEW

**Comment by elextr** [comment]
I was just about to mention html4/5 :)

Also the attribute needs documenting in the user guide.

There are two new languages ahead of you in the PR queue which "should" get committed this weekend.  Could you include changes to them them after they are committed please.

**Comment by aerostitch** [comment]
You read my mind!
I was just about to begin to write the documentation about that! (was looking for the right file!)
I'll commit that in the afternoon.

No problem for the new languages. I'll do the change as soon as they are available.

**Comment by aerostitch** [comment]
Integrated new languages but it seems the rebase of the repo with the upstream brought a little mess in commits.
Don't know how to fix this.

**Comment by elextr** [comment]
`git rebase --interactive` probably can (with _real_ care)

But also, can you put your stuff in a branch, not in master, makes it easier (and safer) to test since its isolated from other peoples changes.

**Comment by aerostitch** [comment]
Actually that's what I've done afterwards (creating a new branch in my fork) but I can't figure out how to change the pull request's branch. Do you want me to close this one and create a new pull request?
The Branch I'm talking about is: "update_bottom_text"

**Comment by aerostitch** [comment]
I close this PR as I cleaned up everything in a new branch and made a new PR for this: https://github.com/asciidoc/asciidoc/pull/9 .
Thanks for the help.
Joseph

**Pull request closed without merging**
