### PR TITLE
Closing html5 backend void tags

### PR DESCRIPTION
**Pull request by aerostitch**
Hi guys,

Just for a little cleanup, I closed all void tags (br, hr, img, link, meta...) of the html5 backend.
I don't think it's really mandatory but I find it little cleaner to do so.

Best, 
Joseph

### CODE REVIEW

**Comment by florentx** [comment]
Even if self-closing tags are accepted in HTML 5, I have a preference for keeping it simple (i.e. not closing).

References:
- http://www.w3.org/TR/html5/syntax.html#start-tags 8.1.2.1 (bullet 6)
- http://www.colorglare.com/2014/02/03/to-close-or-not-to-close.html

**Comment by mojavelinux** [comment]
I support this option in Asciidoctor if the backend to xhtml5.

If this change is made to the html5 backend, it should be done
conditionally (check for the x at the beginning of the backend). html5 and
xhtml5 are different and we should honor this choice.

To implement this idea, you can create a new backend that's called xhtml5
and extends from html5 and sets html-syntax to xml. Then, use conditional
attributes in the html5 backend to add the slash for voids elements and
gives a value for boolean attributes in the html.

Another option is to skip creating the backend & just recognize the
html-syntax attribute (default sgml).

**Comment by aerostitch** [comment]
Hi,

I've created a new backend closing the void elements of html5.
But I'm not completely sure of the additions provided by a new backend that only closes the void tags.

Best,
Joseph

**Comment by aerostitch** [comment]
I'll close that. I don't think it's worth spending the time to move it to the python3 implementation.

**Comment by mojavelinux** [comment]
If you were to pursue, I would recommend honoring the htmlsyntax attribute instead of creating an entirely new backend which is mostly a duplicate. For details, see https://asciidoctor.org/docs/user-manual/#xhtml.

**Pull request closed without merging**
