### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by jghub**
removed one typo introduced previously and, more importantly, tried to rephrase and slightly restructure the latexmath/mathjax related part of the user guide. mathjax is discussed first and the limitations implied by the mathml route (notably that many browsers simply don' t support it) is mentioned. I think the manual
should leave the (probably correct) impression that the user should leave mathml alone and stay with latex math and mathjax.

### CODE REVIEW

**Comment by jghub** [comment]
regarding ci 867f284: the patch ensures that arguments to the text-based browser call (w3m, lynx) can be passed via `a2x.conf like`LYNX = "lynx -width-120". this  is not possible otherwise. I believe the output width should be user-settable in this way. for this reason I also removed the hardcoded `col' setting in the`w3m' block.

**Comment by elextr** [comment]
ahhhh, the command string commit needs to be removed since it now conflicts with the one just merged.

**Comment by jghub** [comment]
IIRC, this is pull request has become obsolete (you might recall that I had to start over by forking and clonding asciidoc a second time (as you advised as the easiest solution, which in fact it was)   since something was messed up. so I don't have the first fork/clone of the repo with these checkins anymore (deleted it on github and also locally). I could not retract the pull request myself (seemingly) and was under the impression you would do that in due time (i.e. reject it or however it is done). to make a long story short: could you just throw this PR away?

**Comment by jghub** [comment]
this concerns also PR 22: that, to was done from my first fork of asciidoc (no deceased ...) and should be removed/rejected/closed

**Comment by jghub** [comment]
and apologies for any confusion possibly  caused...

**Comment by elextr** [comment]
Ok, closed

**Pull request closed without merging**
