### PR TITLE
Filter latex svg

### PR DESCRIPTION
**Pull request by sm0svx**
I wanted better looking and scalable Latex math so I hacked the Latex filter a bit. I have tried the different options for getting math formulas into documents and the filter approach seem to be the most portable one if one wants to generate multiple document formats (e.g. pdf and html).

The generated PNG images does not scale well when zooming in on a web page for example. This is why I have now added support for generating SVG images, which are scalable. The dvisvgm utility is used to do that. Generating PNG images is still the default unless the "imgfmt" attribute is set to "svg". I also added a "latex-imgfmt" attribute that do the same thing. The thought was that the former (the shorter one) can be used to change the format of one image while the latter (the longer one) can be set globally. I don't know if this is the right thing to do. Please tell me if there is a better way of doing it.

Usage may look like this:

``` AsciiDoc
:latex-imgfmt: svg

[latex]
--
\begin{equation*}
X(\omega) &= \sum_{-\infty}^\infty x(n) e^{-j \omega n}
\end{equation*}
--
```

### CODE REVIEW

**Comment by elextr** [comment]
You also need to document your new attributes in the source of http://asciidoc.org/latex-filter.html in doc/latex-filter.txt.

**Comment by sm0svx** [comment]
OK, I'll do that.

**Comment by sm0svx** [comment]
I think I have now properly updated all documentation for the Latex filter.

**Comment by mojavelinux** [comment]
+1 Nice work!

**Comment by sm0svx** [comment]
Thanks :-)

**Pull request merged**
